### ISSUE TITLE
how to connect to your fix api server?

### ISSUE THREAD

**Issue by gpmn** [FXCMAPI/FIXAPI#2]
[SESSION]
SocketConnectHost=fixdemo.fxcorporate.com
SocketConnectPort=<PORT>

according to your configure file, which port?

**Comment by ghost** [comment]
FIX credentials are per username, there is no generic FIX connection.

Daniel

CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

76.88% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors as you could sustain losses in excess of deposits. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. For clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD"), retail clients could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds and professional clients could sustain losses in excess of deposits. Prior to trading any products offered by Forex Capital Markets Limited<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM Australia Pty. Limited<https://www.fxcm.com/au/>, FXCM South Africa (PTY) Ltd<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is an operating subsidiary within the FXCM Group. FXCM Markets is not regulated and not subject to the regulatory oversight that govern other FXCM Group entities, which includes but is not limited to the Financial Conduct Authority, Financial Sector Conduct Authority, and the Australian Securities and Investments Commission. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by ghost** [comment]
please apply a demo account and send to us, we will assign you FIX credentials 
thanks
Lei
